---
# Grafana role defaults
# User-configurable settings are in inventory.yaml

# Helm configuration
grafana_helm_repo_name: grafana
grafana_helm_repo_url: https://grafana.github.io/helm-charts
grafana_helm_chart_name: grafana

# Storage configuration
grafana_name: grafana
grafana_storage_class: '{{ grafana_name }}-storage'
grafana_storage_size: 5Gi
grafana_dir: /scout/monitoring/grafana

# Branding
grafana_app_name: Scout Monitoring
grafana_logo_path: '{{ scout_repo_dir }}/launchpad/public/scout.png'

# Alert configuration
grafana_alert_contact_point: slack # email or slack
grafana_smtp_host: '' # Include the port in the value
grafana_smtp_user: ''
grafana_smtp_password: ''
grafana_smtp_from_address: ''
grafana_smtp_from_name: 'Scout'
grafana_smtp_skip_verify: false
grafana_email_recipients: ['']

# Dashboard and alert paths
grafana_dashboards_path: '{{ role_path }}/files/dashboards'
grafana_alerts_path: '{{ role_path }}/templates/alerts'
grafana_contact_points_path: '{{ role_path }}/templates/contact-points'

# Storage definitions
grafana_storage_definitions:
  - name: '{{ grafana_name }}'
    size: '{{ grafana_storage_size }}'
    path: '{{ grafana_dir }}'
    pv_name: '{{ grafana_name }}-pv'
    storage_class_name: '{{ grafana_storage_class }}'

# Resource configuration (dev defaults)
grafana_resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
