---
- name: Create namespace
  ansible.builtin.include_role:
    name: scout_common
    tasks_from: namespace
  vars:
    ns: '{{ grafana_namespace }}'

- name: Create SMTP secret
  no_log: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: smtp-grafana
        namespace: '{{ grafana_namespace }}'
        labels:
          grafana_alert: '1'
      type: Opaque
      stringData:
        user: '{{ grafana_smtp_user }}'
        password: '{{ grafana_smtp_password }}'
  when: grafana_alert_contact_point == 'email'

- name: Configure Grafana resources
  delegate_to: localhost
  environment:
    K8S_AUTH_KUBECONFIG: '{{ local_kubeconfig_yaml }}'
  block:
    - name: Find all Grafana dashboards
      ansible.builtin.find:
        paths: '{{ grafana_dashboards_path }}'
        patterns: '*.json.j2'
      register: dashboard_templates

    - name: Create ConfigMap for each Grafana dashboard
      no_log: true
      vars:
        dashboard_filename: '{{ item.path | basename | regex_replace(".json.j2$", ".json") }}'
        dashboard_content_b64: >-
          {{ (lookup("template", item.path, variable_start_string="[%", variable_end_string="%]") | b64encode) }}
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: '{{ item.path | basename | regex_replace(".json.j2$", "") }}'
            namespace: '{{ grafana_namespace }}'
            labels:
              grafana_dashboard: '1'
          binaryData: '{{ {dashboard_filename: dashboard_content_b64} }}'
      loop: '{{ dashboard_templates.files }}'
      loop_control:
        label: '{{ item.path | basename }}'

    - name: Find all Grafana alerts
      ansible.builtin.find:
        paths: '{{ grafana_alerts_path }}'
        patterns: '*.json.j2'
      register: alert_templates

    - name: Create ConfigMap for each Grafana alert
      no_log: true
      vars:
        alert_filename: '{{ item.path | basename | regex_replace(".json.j2$", ".json") }}'
        alert_content_b64: >-
          {{ (lookup("template", item.path, variable_start_string="[%", variable_end_string="%]") | b64encode) }}
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: '{{ item.path | basename | regex_replace(".json.j2$", "") }}'
            namespace: '{{ grafana_namespace }}'
            labels:
              grafana_alert: '1'
          binaryData: '{{ {alert_filename: alert_content_b64} }}'
      loop: '{{ alert_templates.files }}'
      loop_control:
        label: '{{ item.path | basename }}'

    - name: Create Grafana notification policy as ConfigMap
      vars:
        notification_policy_content_b64: >-
          {{ (lookup('template', 'notification-policy.yaml.j2', variable_start_string='[%', variable_end_string='%]') | b64encode) }}
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: notification-policy
            namespace: '{{ grafana_namespace }}'
            labels:
              grafana_alert: '1'
          binaryData:
            notification-policy.yaml: '{{ notification_policy_content_b64 }}'
      when: >
        (grafana_alert_contact_point == 'slack' and slack_channel_id != '' and slack_token != '') or
        (grafana_alert_contact_point == 'email' and grafana_smtp_host != '' and grafana_smtp_user != '')

    - name: Find all Grafana contact points
      ansible.builtin.find:
        paths: '{{ grafana_contact_points_path }}'
        patterns: '*.json.j2'
      register: contact_point_templates

    - name: Create Secret for each Grafana contact point
      no_log: true
      vars:
        contact_point_filename: '{{ item.path | basename | regex_replace(".json.j2$", ".json") }}'
        contact_point_content_b64: >-
          {{ (lookup("template", item.path, variable_start_string="[%", variable_end_string="%]") | b64encode) }}
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: '{{ item.path | basename | regex_replace(".json.j2$", "") }}'
            namespace: '{{ grafana_namespace }}'
            labels:
              grafana_alert: '1'
          type: Opaque
          data: '{{ {contact_point_filename: contact_point_content_b64} }}'
      loop: '{{ contact_point_templates.files }}'
      when: >-
        grafana_alert_contact_point in (item.path | basename) and
        (
          ('slack' in (item.path | basename) and slack_channel_id != '' and slack_token != '') or
          ('email' in (item.path | basename) and grafana_smtp_host != '' and grafana_smtp_user != '')
        )
      loop_control:
        label: '{{ item.path | basename }}'

    - name: Create OAuth2 Client Secret
      no_log: true
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: keycloak-grafana-client-secret
            namespace: '{{ grafana_namespace }}'
            labels:
              grafana_alert: '1'
          type: Opaque
          stringData:
            client-secret: '{{ keycloak_grafana_client_secret }}'

    - name: Create postgres datasource secret
      no_log: true
      vars:
        postgres_datasource_content_b64: >-
          {{ (lookup('template', 'datasources/postgres-datasource.yaml.j2', variable_start_string='[%', variable_end_string='%]') | b64encode) }}
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-ingest-db-secret
            namespace: '{{ grafana_namespace }}'
            labels:
              grafana_datasource: 'true'
          data:
            pg-db.yaml: '{{ postgres_datasource_content_b64 }}'

- name: Deploy Grafana
  ansible.builtin.include_role:
    name: scout_common
    tasks_from: deploy_helm_chart
  vars:
    helm_chart_name: '{{ grafana_helm_chart_name }}'
    helm_chart_ref: '{{ grafana_helm_repo_name }}/{{ grafana_helm_chart_name }}'
    helm_chart_namespace: '{{ grafana_namespace }}'
    helm_repo_name: '{{ grafana_helm_repo_name }}'
    helm_repo_url: '{{ grafana_helm_repo_url }}'
    helm_chart_version: '{{ grafana_helm_chart_version }}'
    helm_chart_create_namespace: false
    helm_chart_values: "{{ lookup('template', 'grafana.values.yaml.j2') | from_yaml }}"
