slice_name: Count
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  metric: count
  adhoc_filters:
    - clause: WHERE
      subject: message_dt
      operator: TEMPORAL_RANGE
      comparator: No filter
      expressionType: SIMPLE
  subheader: Radiology Reports
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
    - 1
  annotation_layers: []
query_context: '{"datasource": {"id": 1, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "message_dt", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"having": "", "where": ""}, "applied_time_extras": {}, "columns": [],
  "metrics": ["count"], "annotation_layers": [], "series_limit": 0, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}}], "form_data":
  {"datasource": "1__table", "viz_type": "big_number_total", "metric": "count", "adhoc_filters":
  [{"clause": "WHERE", "subject": "message_dt", "operator": "TEMPORAL_RANGE", "comparator":
  "No filter", "expressionType": "SIMPLE"}], "subheader": "Radiology Reports", "header_font_size":
  0.4, "subheader_font_size": 0.15, "y_axis_format": "SMART_NUMBER", "time_format":
  "smart_date", "extra_form_data": {}, "dashboards": [1], "force": false, "result_format":
  "json", "result_type": "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 1773eb3a-1525-4116-843c-921e3431b292
version: 1.0.0
dataset_uuid: 14cdaed5-905e-499a-b020-13e1b54097c8
