slice_name: Service Name
description: null
certified_by: null
certification_details: null
viz_type: word_cloud
params:
  datasource: 1__table
  viz_type: word_cloud
  slice_id: 5
  series: service_name
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: message_dt
  row_limit: 250
  sort_by_metric: true
  size_from: 10
  size_to: 70
  rotation: flat
  color_scheme: presetColors
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"message_dt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["service_name"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":250,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"word_cloud","slice_id":5,"series":"service_name","metric":"count","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"message_dt"}],"row_limit":250,"sort_by_metric":true,"size_from":10,"size_to":70,"rotation":"flat","color_scheme":"presetColors","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9cfca38a-5ddf-424c-a078-e653fb2cd270
version: 1.0.0
dataset_uuid: 14cdaed5-905e-499a-b020-13e1b54097c8
