slice_name: Sex
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 1__table
  viz_type: pie
  slice_id: 1
  groupby:
  - sex
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_tw7iiia3b5_nwltwjvfc0c
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: message_dt
  - clause: WHERE
    comparator:
    - null
    - ''
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_rnqzc3awt_xbnx1jgcufp
    isExtra: false
    isNew: false
    operator: NOT IN
    operatorId: NOT_IN
    sqlExpression: null
    subject: sex
  row_limit: 100
  sort_by_metric: true
  color_scheme: presetColors
  show_labels_threshold: 5
  roseType: radius
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"message_dt","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"sex","op":"NOT IN","val":[null,""]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["sex"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":100,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"pie","slice_id":1,"groupby":["sex"],"metric":"count","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_tw7iiia3b5_nwltwjvfc0c","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"message_dt"},{"clause":"WHERE","comparator":[null,""],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_rnqzc3awt_xbnx1jgcufp","isExtra":false,"isNew":false,"operator":"NOT
  IN","operatorId":"NOT_IN","sqlExpression":null,"subject":"sex"}],"row_limit":100,"sort_by_metric":true,"color_scheme":"presetColors","show_labels_threshold":5,"roseType":"radius","show_legend":true,"legendType":"scroll","legendOrientation":"top","label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","show_labels":true,"labels_outside":true,"outerRadius":70,"innerRadius":30,"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 3124770b-a500-4b7f-8d15-2762aec1e511
version: 1.0.0
dataset_uuid: 14cdaed5-905e-499a-b020-13e1b54097c8
