apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "launchpad.fullname" . }}-config
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
data:
  config.js: |
    window.scoutConfig = {
      enableChat: {{ .Values.enableChat | default false }},
      showPlaybooks: {{ .Values.showPlaybooks | default false }}
    };
