---
# Defaults for keycloak role
# User-configurable settings are in inventory.yaml

keycloak_version: 26.4.2

# Keycloak image
keycloak_image_repository: ghcr.io/washu-tag/keycloak
keycloak_image_tag: '{{ keycloak_version }}'

# Air-gapped artifact configuration
keycloak_artifact_download_timeout: 300

# Keycloak operator version and artifact URLs
keycloak_operator_version: '{{ keycloak_version }}'
keycloak_crd_url: 'https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/{{ keycloak_operator_version }}/kubernetes/keycloaks.k8s.keycloak.org-v1.yml'
keycloak_realmimport_crd_url: 'https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/{{ keycloak_operator_version }}/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml'
keycloak_operator_url: 'https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/{{ keycloak_operator_version }}/kubernetes/kubernetes.yml'

# Keycloak Config CLI
keycloak_config_cli_helm_chart_url: 'https://adorsys.github.io/keycloak-config-cli/helm-charts/keycloak-config-cli-{{ keycloak_config_cli_helm_chart_version }}.tgz'

# Keycloak admin console credentials (password must be defined in inventory)
keycloak_bootstrap_admin_user: admin

# Keycloak database credentials (password must be defined in inventory)
keycloak_postgres_user: keycloak

# SMTP configuration for email notifications
keycloak_smtp_host: mailhog-service.mailhog
keycloak_smtp_port: '1025'
keycloak_smtp_from: example@example.com
keycloak_smtp_from_display_name: Scout
keycloak_smtp_reply_to: ''
keycloak_smtp_reply_to_display_name: ''
keycloak_smtp_envelope_from: ''
keycloak_smtp_auth: ''
keycloak_smtp_ssl: 'false'
keycloak_smtp_starttls: 'false'
keycloak_smtp_debug: 'false'

# Identity Provider configuration
keycloak_default_provider: github
