---
# Kubernetes deployment tasks for Orthanc
# These tasks run on the server host (which has access to k3s_cluster inventory variables)

- name: Create Orthanc namespace
  kubernetes.core.k8s:
    name: '{{ orthanc_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Create PersistentVolumeClaim for Orthanc data
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: orthanc-data-pvc
        namespace: '{{ orthanc_namespace }}'
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: '{{ orthanc_storage_size }}'
        storageClassName: '{{ orthanc_storage_class | default(omit) }}'

- name: Create Orthanc conf secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: orthanc-secret
        namespace: '{{ orthanc_namespace }}'
      type: Opaque
      stringData:
        'orthanc.json': "{{ lookup('template', 'orthanc-conf.json.j2') | to_nice_json }}"

- name: Deploy Orthanc
  ansible.builtin.include_role:
    name: scout_common
    tasks_from: deploy_helm_chart
  vars:
    helm_chart_name: orthanc
    helm_chart_ref: '{{ scout_repo_dir }}/helm/orthanc'
    helm_chart_namespace: '{{ orthanc_namespace }}'
    helm_chart_create_namespace: false
    helm_chart_timeout: 2m
    helm_chart_values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

# Populate PACS with test data (optional)
- name: Populate Orthanc with test data
  ansible.builtin.include_tasks: populate.yaml
  when: orthanc_populate is defined
